//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumbleJungle.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RumbleJungle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu M238.69,136.32a4,4,0,0,0,1.55-.3c1.62-.64,3.26-1.21,4.9-1.7a4.2,4.2,0,1,0-2.41-8c-1.87.56-3.75,1.21-5.59,1.94a4.2,4.2,0,0,0,1.55,8.1Z M81.35,276.32a81.67,81.67,0,0,0,18.26,28,60.27,60.27,0,0,0,38,17.52c1.39.1,2.73.15,4,.15,27.76,0,39.14-22,42-29a3.75,3.75,0,0,0,.25-.85c3.93-.85,11-1.86,16.74-.73,1.72.9,3.49,1.79,5.34,2.64,57.71,26.47,70.76,62,69.69,95a52.08,52.08,0,0,0-14.64-12.9c-4.4-9.52-17-30.72-43.23-35.34a57.88,57.88,0,0,0-37.49,6.47c-14.28,7.79-49.31,24.52-66,11.82a4.2,4.2,0,0,0-6.55,4.6c.16.49,3.87,1 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string CarnivorousPlant {
            get {
                return ResourceManager.GetString("CarnivorousPlant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu M92.49,44.81a27.85,27.85,0,0,0-.25-8.87l-2,.22c0,1.3-1,3.81-2.29,6.27a28.09,28.09,0,0,1-7.38-7.64c4.13-9,2.77-9.84,2.18-10.2a3,3,0,0,0-3.06.33,1.54,1.54,0,0,0-.74-.84c-1.14-.57-4.48.77-8.23,2.67-14.64-3-29.76-.06-32.55,1-2.2.85-9.16.64-11.74.49A28.27,28.27,0,0,0,8.57,36.44,14.11,14.11,0,0,0,4.72,43.2c-1.79.84-4.25,3.22-3.4,7.71,1,5.29,1.57,6.45,1.67,6.63l1.75-1s-.52-1.11-1.46-6a5,5,0,0,1,1-4.57c-.36,4.88,1.28,9.51,2.1,11.84.2.56.37,1,.43,1.29.25,1-2.15,4.2-4.55,6.51l-.33.31.9,19.72h8.1l-.21-1.18a81.09,81.09 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string WildPig {
            get {
                return ResourceManager.GetString("WildPig", resourceCulture);
            }
        }
    }
}
