//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumbleJungle.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RumbleJungle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu m 92.49 44.81 a 27.85 27.85 0 0 0 -0.25 -8.87 l -2 0.22 c 0 1.3 -1 3.81 -2.29 6.27 a 28.09 28.09 0 0 1 -7.38 -7.64 c 4.13 -9 2.77 -9.84 2.18 -10.2 a 3 3 0 0 0 -3.06 0.33 1.54 1.54 0 0 0 -0.74 -0.84 c -1.14 -0.57 -4.48 0.77 -8.23 2.67 -14.64 -3 -29.76 -0.06 -32.55 1 -2.2 0.85 -9.16 0.64 -11.74 0.49 A 28.27 28.27 0 0 0 8.57 36.44 14.11 14.11 0 0 0 4.72 43.2 c -1.79 0.84 -4.25 3.22 -3.4 7.71 1 5.29 1.57 6.45 1.67 6.63 l 1.75 -1 c 0 0 -0.52 -1.11 -1.46 -6 a 5 5 0 0 1 1 -4.57 c -0.36 4.88 1.28 9.51 2.1 11.84 0.2 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string WildPig {
            get {
                return ResourceManager.GetString("WildPig", resourceCulture);
            }
        }
    }
}
